### ISSUE TITLE
`exwm-xim` does not work

### ISSUE THREAD

**Issue by InAnYan** [emacs-exwm/exwm#106]
Hi! I've been configuring my Emacs and EXWM for a long time and I needed a way for handling different keyboard layouts.

Initially I tried to use plain `setxkbmap`, but it had some issues (I should make a separate issue for this).

I really like `exwm-xim` module, however, it seems not working.

What I have in my configuration:

1. EXWM is started with a shell script in `lightdm`, this shell script looks like this:

```sh
# Taken and modified from: https://github.com/daviwil/emacs-from-scratch/blob/2805904966dbd5810ee735e25c4b427014761be5/Desktop.org#desktop-file.

# Taken from: https://weblog.zamazal.org/more-fun-with-exwm/.
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim

# Run the screen compositor
picom &

# Taken from: https://github.com/polybar/polybar/issues/763#issuecomment-331604987.
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload iay &
done

# Fire it up.
exec emacs -mm --debug-init -l /home/ruslan/.emacs.d/desktop.el

```

2. Then, in `desktop.el` (which is a file that is called after `init.el`, when I use Emacs as a DE), I use `use-package` on EXWM and after `(exwm-enable)` I put those lines:

```elisp
  (exwm-xim-mode 1)
  (push ?\C-\\ exwm-input-prefix-keys)
```

Just like in tutorials and docs.

However, Emacs buffers work perfectly, but in GUI apps like Firefox, Libreoffice, Telegram Desktop, it doesn't work :(

Would appreciate any help

**Comment by InAnYan** [comment]
Found a fix! This problem is related to `evil`!

https://www.reddit.com/r/emacs/comments/i2pflu/comment/g5hxdst/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

The fix is to add this in configuration (I put it directly after `evil-enable`):

```elisp
(evil-set-initial-state 'exwm-mode 'emacs)
```

**Comment by Stebalien** [comment]
Interesting. I don't use xim but do have the following in my `init.el`:

```elisp
(define-advice evil-disabled-buffer-p (:before-until () no-exwm)
  (eq major-mode 'exwm-mode))
```

@minad I don't really want to add a ton of evil hacks to EXWM, but how would you feel about some advice like this? Defaulting to `'emacs` state also works but isn't as effective as simply disabling Evil mode for EXWM buffers entirely.

**Comment by minad** [comment]
@Stebalien I am pretty much against adding Evil-specific workarounds to EXWM. How many of such advices would be needed? Generally I prefer if Evil-specific integrations are collected in evil-collection. The question here is also if putting the check into Evil itself wouldn't be more appropriate, given that it would avoid an advice?

**Comment by Stebalien** [comment]
Yeah, I generally agree. Although in this case the number of hacks should be limited to exactly one because that hack simply disables Evil. But it's still a hack. I'll make a PR to evil-collection.

**Comment by minad** [comment]
Wouldn't it be better to add some `evil-exclude-buffers` customization variable to Evil directly? I imagine that disabling Evil is not only relevant in EXWM buffers and it could be prepopulated accordingly in Evil directly. I may as well be wrong since I don't have much experience with Evil. I tried it only briefly.
