### ISSUE TITLE
Window losing focus with `evil-mode`

### ISSUE THREAD

**Issue by LemonBreezes** [emacs-exwm/exwm#11]
Hi. I haven't used EXWM for a few months, but when I used it, the biggest issue for me was EXWM windows randomly losing focus. This seemed to be much worse when using `evil-mode` with EXWM.

**Comment by Stebalien** [comment]
I use both evil and EXWM and haven't had an issue like this in quite a while. Can you re-test? Quite a few bugs have been fixed in the last few months and there's not much to go on here that might help us reproduce the issue.

Also, are you using multiple monitors?

**Comment by LemonBreezes** [comment]
> Do you use `mouse-autoselect-window`?

No.

> Also, are you using multiple monitors?

No. 

I am going to close this issue since I am not currently using EXWM and when I try it out again with Evil, I'll reopen if it reoccurs. Thanks for giving me information about the latest developments.

**Comment by Stebalien** [comment]
Please do! Also, consider calling `exwm-debug` to enable logging. That will give us a pretty thorough trace for us to debug.
