### ISSUE TITLE
Set default directory to match process

### ISSUE THREAD

**Issue by Stebalien** [emacs-exwm/exwm#12]
I've configured EXWM to set the default directory of an X window to the processes default directory and I'm wondering if others would find this behavior useful/desirable. Specifically:

```elisp
(add-hook 'exwm-manage-finish (lambda ()
  (when-let* ((id (exwm--buffer->id (current-buffer)))
              (response (xcb:+request-unchecked+reply exwm--connection
                            (make-instance 'xcb:ewmh:get-_NET_WM_PID :window id)))
              (pid (slot-value response 'value))
              (cwd (file-chase-links (format "/proc/%d/cwd" pid) 1)))
    (setq default-directory (if (file-accessible-directory-p cwd)
                                (file-name-as-directory cwd)
                              user-home-directory)))))
```

Of course, this won't keep the `default-directory` in-sync with the X window, but that usually only matters for shells. I have another script to update the default directory as it changes (and intend to add this to either the wiki or some form of contrib directory).

<details>
Elisp:

```elisp
(defun exwm-set-window-directory (wid dd)
  (when-let ((buf (exwm--id->buffer wid)))
    (with-current-buffer buf (setq default-directory dd))))
```

Zsh:

```zsh
if [[ -n "$INSIDE_EMACS" ]] && [[ -n "$EXWM" ]] && [[ -n "$WINDOWID" ]]; then
    __exwm_chpwd() {
        # Only apply directory changes in the root shell.
        [[ "$ZSH_SUBSHELL" -eq 0 ]] || return
        # Emacsclient sets the 'default-directory' to the caller's CWD, so
        # this always works and saves us from having to pass it in (and escape
        # it).
        emacsclient -e "(exwm-set-window-directory $WINDOWID default-directory)" \
                    > /dev/null
    }
    __exwm_chpwd
    chpwd_functions+=(__exwm_chpwd)
fi
```

(where `$WINDOWID` is set by my terminal and I set `$EXWM` myself).
</details>

**Comment by minad** [comment]
> I've configured EXWM to set the default directory of an X window to the processes default directory and I'm wondering if others would find this behavior useful/desirable.

Sounds like a good idea. Right now I set the default directory to ~/ in all my EXWM buffers, but that's far from ideal.

> Of course, this won't keep the default-directory in-sync with the X window, but that usually only matters for shells.

Shells often update the title of the window, so maybe it would work if we refresh the default directory in an exwm-update-title-hook?

How do you suggest to enable this behavior? Install the hooks by default or optionally?

**Comment by Stebalien** [comment]
> Shells often update the title of the window, so maybe it would work if we refresh the default directory in an exwm-update-title-hook?
> How do you suggest to enable this behavior? Install the hooks by default or optionally?

For shells, I'd provide a hook but not enable it by default. It'll have trouble, with, e.g., SSH and would conflict with "better" ways to set the default directory.

As for the _initial_ default directory, I'd set that in manage before calling any hooks. That way the user can easily override it but they get a sane default.

**Comment by minad** [comment]
> For shells, I'd provide a hook but not enable it by default. It'll have trouble, with, e.g., SSH and would conflict with "better" ways to set the default directory.

Makes sense. In a shell with ssh one may even want to change the default-directory to a Tramp path.

I currently try out the following function based on your code. I've added it to the manage finish hook. So far it works well.

~~~ elisp
(defun +exwm-update-default-directory ()
  "Set `default-directory' to current working directory of process."
  (setq-local default-directory
              (if-let ((id (exwm--buffer->id (current-buffer)))
                       (response (xcb:+request-unchecked+reply exwm--connection
                                     (make-instance 'xcb:ewmh:get-_NET_WM_PID :window id)))
                       (pid (slot-value response 'value))
                       (cwd (file-chase-links (format "/proc/%d/cwd" pid) 1))
                       ((file-accessible-directory-p cwd)))
                  (file-name-as-directory cwd)
                (expand-file-name "~/"))))
~~~

**Comment by minad** [comment]
@medranocalvo Yes, we could do that as a fallback. I don't see a problem, except maybe the efficiency. Starting a process is a bit more expensive than reading a symlink from /proc. Otoh we can also keep things as is. Then the default-directory in exwm-mode buffers is consistently set to ~/, which is also not that bad.
