### ISSUE TITLE
Mini frame garbled

### ISSUE THREAD

**Issue by yusi1** [emacs-exwm/exwm#23]
When I use mini frame inside EXWM, it appears garbled, I have attached a screenshot.

![2024-03-02-001629_1920x1080_scrot](https://github.com/emacs-exwm/exwm/assets/82241382/da069104-b5ad-4ee4-a608-fdce73fac865)

**Comment by Stebalien** [comment]
That looks like a graphics driver issue (possibly related to transparency), not something we're likely going to be able to do anything about.

Out of curiosity, what hardware do you have? CPU + GPU?

**Comment by yusi1** [comment]
> That looks like a graphics driver issue (possibly related to transparency), not something we're likely going to be able to do anything about.
> 
> Out of curiosity, what hardware do you have? CPU + GPU?

Ryzen 5 5600 + RX 580

**Comment by yusi1** [comment]
I use picom as a compositor if that is of any help

**Comment by yusi1** [comment]
Nevermind, when the compositor is killed same thing happens

**Comment by Stebalien** [comment]
- Does this happen without EXWM?
- Disable transparency for both Emacs and the mini-frame.
- Make sure everything is up to date. Although I'm not too hopeful here given that your card is 7 years old.

> Nevermind, when the compositor is killed same thing happens

You could also try playing around with different picom backends.

**Comment by yusi1** [comment]
> * Does this happen without EXWM?
> * Disable transparency for both Emacs and the mini-frame.
> * Make sure everything is up to date. Although I'm not too hopeful here given that your card is 7 years old.
> 
> > Nevermind, when the compositor is killed same thing happens
> 
> You could also try playing around with different picom backends.

1: no, i tried a tiling window manager with picom and it does not occur
2: with transparency being disabled same thing occurs
3: everything is up to date and my distro is Arch Linux
4: tried all three picom backends "glx", "xrender", "xr_glx_hybrid" and same thing happened with all three

It doesn't matter I guess as I can just disable mini-frame-mode, not a serious problem or anything, but I did see people with EXWM
use mini-frame-mode and it looked nice which is the only reason I was using it.

**Comment by Stebalien** [comment]
This is... very strange. You're saying that you don't see this issue when you use mini-frame _without_ EXWM?

**Comment by yusi1** [comment]
> This is... very strange. You're saying that you don't see this issue when you use mini-frame _without_ EXWM?

Yes

**Comment by yusi1** [comment]
I used picom on a tiling wm and I did not see the issue, in KDE Plasma X11 & Wayland the issue was not there

**Comment by yusi1** [comment]
Maybe it is my configuration?

**Comment by Stebalien** [comment]
> with transparency being disabled same thing occurs

Just to confirm, you disabled transparency for the mini-frame frame (i.e., you're not setting any alpha/transparency frame parameters).

Other than that... maybe a config difference between KDE & your Emacs session? I've seen this kind of glitching before, but it always has to do with compositors and transparency.

---

I would try minimizing the differences:

1. Create a clean Emacs config, install EXWM + mini-frame.
2. Launch Emacs with `xinit` directly from a TTY.
3. Text mini-frame (no window manager, no EXWM).
4. Enable EXWM.
5. Test mini-frame again.

**Comment by yusi1** [comment]
> > with transparency being disabled same thing occurs
> 
> Just to confirm, you disabled transparency for the mini-frame frame (i.e., you're not setting any alpha/transparency frame parameters).
> 
> Other than that... maybe a config difference between KDE & your Emacs session? I've seen this kind of glitching before, but it always has to do with compositors and transparency.
> 
> I would try minimizing the differences:
> 
>     1. Create a clean Emacs config, install EXWM + mini-frame.
> 
>     2. Launch Emacs with `xinit` directly from a TTY.
> 
>     3. Text mini-frame (no window manager, no EXWM).
> 
>     4. Enable EXWM.
> 
>     5. Test mini-frame again.

Yep, I completely disabled all transparency.

The only difference between my KDE and EXWM session is that when I load into the EXWM session it loads my EXWM config and some other package configs.

I created a clean Emacs config and just loaded the exwm example config and mini-frame:
1: Mini-frame does not work in TTYs for some reason
5: Same garbled issue, except the garbling is black maybe because I didn't set a wallpaper or something.

**Comment by yusi1** [comment]
Maybe I can try in a VM incase it is an issue with something on my system

**Comment by yusi1** [comment]
Hmm, it does not occur in a Kubuntu VM. No garbling issues.

**Comment by yusi1** [comment]
![VirtualBox_kubuntu_09_03_2024_09_48_15](https://github.com/emacs-exwm/exwm/assets/82241382/c8e0ed80-d4dc-41ac-9c37-b2b179a364bb)

**Comment by yusi1** [comment]
kubuntu vm uses emacs 28.2 and archlinux has emacs 29.2
will see in an archlinux vm if same issue occurs

**Comment by yusi1** [comment]
The issue occurs in the ArchLinux VM which uses Emacs 29.2:
![VirtualBox_EndeavourOS_09_03_2024_10_13_55](https://github.com/emacs-exwm/exwm/assets/82241382/f56eb380-bd2c-4a7a-9996-2a1aa453c5a8)

**Comment by yusi1** [comment]
So something happened between 28.2 and 29.2 that causes mini-frame to be garbled in EXWM.

**Comment by Stebalien** [comment]
>  3: Mini-frame does not work in TTYs for some reason

Not in a TTY, in an X session you start directly from a TTY (without EXWM) to rule out everything else. Although you might need to start some other window manager like i3 to get everything working.

> So something happened between 28.2 and 29.2 that causes mini-frame to be garbled in EXWM.

If it's working in Emacs 29.2 in KDE under _X_, it's not Emacs issue. EXWM isn't responsible for rendering at all, it just tells X where to place the window, so EXWM v no EXWM shouldn't make a difference.

The issue probably lies somewhere in the X configuration (e.g., maybe the wrong X driver?). Or some compositing setting.

**Comment by yusi1** [comment]
> > 3: Mini-frame does not work in TTYs for some reason
> 
> Not in a TTY, in an X session you start directly from a TTY (without EXWM) to rule out everything else. Although you might need to start some other window manager like i3 to get everything working.
> 
> > So something happened between 28.2 and 29.2 that causes mini-frame to be garbled in EXWM.
> 
> If it's working in Emacs 29.2 in KDE under _X_, it's not Emacs issue. EXWM isn't responsible for rendering at all, it just tells X where to place the window, so EXWM v no EXWM shouldn't make a difference.
> 
> The issue probably lies somewhere in the X configuration (e.g., maybe the wrong X driver?). Or some compositing setting.

Ah sorry for not mentioning, but the tests in the VM where done in EXWM in the VM using EXWM's example configuration

**Comment by yusi1** [comment]
> > 3: Mini-frame does not work in TTYs for some reason
> 
> Not in a TTY, in an X session you start directly from a TTY (without EXWM) to rule out everything else. Although you might need to start some other window manager like i3 to get everything working.

Ah okay I misunderstood, I will try that aswell

**Comment by yusi1** [comment]
Ok so I started a tiling window manager from startx without the compositor, ran Emacs, and I activated mini-frame-mode, and the garbling issue is not there.

**Comment by yusi1** [comment]
I'm fairly sure it is a problem with Emacs 29.2, as I tried the same thing in a Kubuntu VM which uses 28.2 (started EXWM with the example config with startx), ran mini-frame-mode and the garbling issue wasn't there.

In the ArchLinux VM, which uses Emacs 29.2, I did the same thing as above, the garbling issue was back.

I did not start a compositor in either VM.

**Comment by Stebalien** [comment]
And you ran the exact same setup with EXWM (and no compositor), and the issue was there?

**Comment by yusi1** [comment]
> And you ran the exact same setup with EXWM (and no compositor), and the issue was there?

The example config or my config?

**Comment by yusi1** [comment]
Oh sorry yes, I used the same config for the Emacs in the tiling window manager that I do for EXWM.

**Comment by yusi1** [comment]
> And you ran the exact same setup with EXWM (and no compositor), and the issue was there?

and the issue was still there without a compositor and same config

**Comment by Stebalien** [comment]
> Oh sorry yes, I used the same config for the Emacs in the tiling window manager that I do for EXWM.

What about starting X the same way? That's what I'm concerned about (same X config, same environment variables, same X resources, etc.).

**Comment by yusi1** [comment]
> > Oh sorry yes, I used the same config for the Emacs in the tiling window manager that I do for EXWM.
> 
> What about starting X the same way? That's what I'm concerned about (same X config, same environment variables, same X resources, etc.).

I'm sorry I do not understand what you mean, the only differences between my xinitrc for the tiling window manager and the xinitrc for EXWM is the last exec line where either I run either the tiling window manager or EXWM.

Both of the xinitrc's have the same environment variables that are exported, and both of them use the same .Xresources file.

I just use the default Xorg configuration for both EXWM and the tiling window manager, I did not tamper with that stuff.

If that is what you meant or maybe I am misunderstanding.

**Comment by Stebalien** [comment]
No, that's what I meant. At this point, I'm just really confused.

**Comment by yusi1** [comment]
Do you have Virtualbox? I can send you a VM image that the issue occurs in.

**Comment by Stebalien** [comment]
Honestly, it's not worth it. There's a good chance it's hardware specific (VMs ultimately use the underlying hardware), or some rendering bug I'm not going to be able to suss out. The fact of the matter is that EXWM _doesn't_ render windows, so the underlying bug is somewhere else (even if it only appears when using EXWM).

**Comment by yusi1** [comment]
Closing as issue is not related to EXWM.

**Comment by tazjin** [comment]
Even though this isn't related to EXWM, I wanted to make one point for you, @yusi1, which might help you with analysing this further. You wrote:

> kubuntu vm uses emacs 28.2 and archlinux has emacs 29.2. So something happened between 28.2 and 29.2 that causes mini-frame to be garbled in EXWM.

The thing is that while these specific versions of emacs might be different, that's no guarantee that *literally everything else* is the same. This includes the X server itself, the config it launches with, the compositors, the libraries Emacs links to, what graphics framework Emacs is linked against and so on.

On legacy distributions that are not as consistent as NixOS/GuixSD it might be very difficult to trace this down to a specific package version, but I'd recommend you look into how *exactly* these two distros build Emacs (which flags, which library versions, ....) and try to find the difference that you're seeing there. If that doesn't help, go up the chain - look at X itself, graphics frameworks and so on.

And once you find it, make sure to file a report in the appropriate place! Good luck :)
