### ISSUE TITLE
Attempts to select 'nil' window

### ISSUE THREAD

**Issue by Stebalien** [emacs-exwm/exwm#28]
I think I've finally tracked down the source of the `(wrong-type-argument window-live-p nil)` error I've been seeing (finally got a backtrace):

https://github.com/emacs-exwm/exwm/blob/182102767e578c4c9556c3fc30135ec8ac7b8471/exwm.el#L512

The cause seems pretty clear: the buffer here may not actually _have_ a current window:

https://github.com/emacs-exwm/exwm/blob/182102767e578c4c9556c3fc30135ec8ac7b8471/exwm.el#L499-L512

`get-buffer-window` is probably returning `nil`.

**Comment by rayslava** [comment]
It seems this is the error that I get from time to time after launching Gnus.
Some windows can't get focus with this error, and switching workspaces leads to random switching to previously active windows from time to time. 

Is there any fix or at least workaround for this one?
