### ISSUE TITLE
Using :hook or :requires with use-package causes EXWM to not load properly

### ISSUE THREAD

**Issue by apsinthium** [emacs-exwm/exwm#34]
I'm running the latest version of Emacs and EXWM on Arch Linux. I've tried two methods of adding hooks inside of a `use-package` form. The first is as follows:

```
(require 'exwm-floating)
(require 'exwm-manage)
(require 'exwm-randr)

(add-hook 'exwm-floating-setup-hook
          'exwm-layout-hide-mode-line)  
(add-hook 'exwm-manage-finish-hook
          'exwm-configure-window)  
(add-hook 'exwm-update-class-hook
          #'(lambda ()
              (exwm-workspace-rename-buffer exwm-class-name)))
(add-hook 'exwm-update-title-hook
          #'(lambda ()
              (exwm-workspace-rename-buffer exwm-title)))
```

This works as expected, but if I try to use `use-package`'s `:hook` or `:requires` optionals then EXWM fails to load:

```
:requires
(exwm-floating exwm-manage exwm-randr)
:hook
(exwm-floating-setup . exwm-layout-hide-mode-line)
(exwm-manage-finish . exwm.configure-window)
(exwm-update-class . (lambda ()
                      (exwm-workspace-rename-buffer exwm-class-name)))
(exwm-update-title . (lambda ()
                      (exwm-workspace-rename-buffer exwm-title)))
```

Having read the [documents](https://github.com/jwiegley/use-package) on `use-package`, I expected the aforementioned to work. Is this an issue with EXWM or the way that I'm trying to implement the code?

**Comment by Stebalien** [comment]
Unfortunately, the "requires" keyword is poorly named.

> the somewhat simpler :requires keyword simply never loads the package if the dependencies are not available at the time the use-package declaration is encountered

Basically, use package isn't loading EXWM in this case because one or more of `exwm-floating`, `exwm-manage`,  `exwm-render` are not already loaded. `:requires foo` is equivalent to `:if (featurep foo)`, not `(require foo)`.

**Comment by apsinthium** [comment]
@Stebalien I see. One more question. What about `:hooks`?

```
(add-hook 'exwm-floating-setup-hook
          'exwm-layout-hide-mode-line)  
(add-hook 'exwm-manage-finish-hook
          'exwm-configure-window)  
(add-hook 'exwm-update-class-hook
          #'(lambda ()
              (exwm-workspace-rename-buffer exwm-class-name)))
(add-hook 'exwm-update-title-hook
          #'(lambda ()
              (exwm-workspace-rename-buffer exwm-title)))
```
Works fine, but when I try: 
```
:hook
(exwm-floating-setup . exwm-layout-hide-mode-line)
(exwm-manage-finish  . exwm.configure-window)
(exwm-update-class   . (lambda ()
                         (exwm-workspace-rename-buffer exwm-class-name)))
(exwm-update-title   . (lambda ()
                         (exwm-workspace-rename-buffer exwm-title)))
```
Then EXWM won't initialize.

**Comment by Stebalien** [comment]
You have a typo in the `exwm-manage-finish` hook.

**Comment by apsinthium** [comment]
That was my fault when sending the reply. However, upon replacing `exwm.configure-window` with `exwm-configure-window` then EXWM still doesn't initialize when using `:hook`. Do you personally use `:hook`; if not could you try for the sake of seeing if it works on your end?

**Comment by Stebalien** [comment]
Can you post the entire config?

**Comment by Stebalien** [comment]
Also, have you checked your messages/warnings buffer for any errors?

**Comment by apsinthium** [comment]
@Stebalien Yes, nothing in *Warnings* and nothing related to EXWM in *Messages*. Here's the full config: https://paste.ofcode.org/39EUrgxRpBbw7cGR3wHC4Ze

Simply commenting out the :hook section and un-commenting the (add-hook 'foo) equivalent will allow the EXWM to launch properly on my end.

**Comment by Stebalien** [comment]
Move your hooks above your config. The rest of your config is getting parsed as "hook" definitions (lines 75-79).

**Comment by apsinthium** [comment]
@Stebalien I did so, but with the same result. I narrowed it down to:

```
(exwm-floating-setup . exwm-layout-hide-mode-line)
```
Commenting this out and instead using:
```
(exwm-floating-setup . (lambda ()
                         (setq mode-line-format nil)))
```

**Comment by Stebalien** [comment]
Hm. That one should have worked.
