### ISSUE TITLE
Modifications to the wiki

### ISSUE THREAD

**Issue by ethanmoss1** [emacs-exwm/exwm#38]
As mentioned in the #20 I am keen to help by adding additional information to the wiki. As summer is coming up i will have some free time to spend contributing. I am however unable to make changes. Is there a mailing list for patches or is there a maintainer list? I have some changes I've done on a working copy of the wiki ready to go. Thanks in advance!

**Comment by minad** [comment]
Thanks. I've enabled write access to the wiki.
