### ISSUE TITLE
 problem with exwm-input-prefix-keys

### ISSUE THREAD

**Issue by myegane49** [emacs-exwm/exwm#39]
there is no way to add s- to the exwm-input-prefix-keys list. also it would be nice to add SPC and f1 to f12 keys to the list.

**Comment by Stebalien** [comment]
Unfortunately, `s-` isn't a prefix. We'd need to add a general `exwm-input-modifier-keys` setting.

> also it would be nice to add SPC and f1 to f12 keys to the list.

You can do that in your own config but I recommend against it (applications frequently bind function keys and I assume you want to be able to type SPC).

**Comment by Stebalien** [comment]
Closing in favor of https://github.com/emacs-exwm/exwm/issues/40 (a more specific feature request).
