### ISSUE TITLE
steam webhelper does not run

### ISSUE THREAD

**Issue by myegane49** [emacs-exwm/exwm#42]
steam webhelper does not run and consequently steam itself

**Comment by Stebalien** [comment]
- Are you seeing any errors?
- Does anything hang?

Also see https://github.com/emacs-exwm/exwm/wiki#how-to-report-a-bug. Specifically, try turning on `exwm-debug` before launching the application. Then post the log.

**Comment by myegane49** [comment]
I realized it was because I have enabled xim for exwm. that was the cause
