### ISSUE TITLE
New release 0.31

### ISSUE THREAD

**Issue by minad** [emacs-exwm/exwm#69]
I'd like to tag the new release 0.31 soon. Originally I had planned to delay this a little longer, maybe after the introduction of an `emacs-wm-mode`, but it turned out that we're using functions only available in Emacs 28 and newer (#68). I fixed this by pulling in the Compat dependency, which I had also planned to do some time soon, also given that Emacs upstream adopted Compat. This means that from Emacs 30 on, depending on Compat will add zero costs, if the Emacs version in use is sufficiently new.

cc @Stebalien

**Comment by Stebalien** [comment]
SGTM. Everything has been pretty stable for me except #64, but that's not new.

**Comment by minad** [comment]
Thanks! Done in https://github.com/emacs-exwm/exwm/commit/512d0f0ef9f02211a463fdae04e6732de80bb5de.
