### ISSUE TITLE
`exwm-workspace--update-workareas` Wrong type argument

### ISSUE THREAD

**Issue by cherrypiejam** [emacs-exwm/exwm#72]
Error message when running `(exwm-workspace--update-workareas)` with the latest commit:

``
exwm-workspace--update-workareas: Wrong type argument: number-or-marker-p, nil
``

Is this function depreciated?

**Comment by Stebalien** [comment]
I can't reproduce locally. Can you run:

    M-x toggle-debug-on-error

reproduce, then post the stack trace?

**Comment by cherrypiejam** [comment]
Ah I didn't know this command. Turns out a package I am using add a hook to `update-workareas` so I need to fix that package. Thanks for helping out!

**Comment by Stebalien** [comment]
Np. I really wish Emacs included stack traces with errors like this by default...
