### ISSUE TITLE
EXWM 0.31 positions frames in a really weird way when with multiple monitors

### ISSUE THREAD

**Issue by qespr** [emacs-exwm/exwm#81]
Probably not a xelb problem since 0.30 depended on xelb 0.20 as well and things _kinda_ worked.

I have 6 monitors, after updating to EXWM 0.31, frames start positioned with significant offset instead of abiding by command in ``exwm-randr-screen-change-hook``. This used to _sometimes_ happen in 0.28, and 0.30 but could be fixed by moving some monitor slightly in ``arandr`` (some race condition?). This workaround no longer works in 0.31 and Emacs frames move in really weird directions, almost random it seems.

I have them ordered as shown in the picture which works (almost) flawlessly in EXWM 0.28 and 0.30
![workingLayout](https://github.com/user-attachments/assets/131c54e4-c60e-4891-b46c-487ae55d0318)

The command (also generated by arandr) is:
``xrandr --output DVI-D-0 --mode 1920x1080 --pos 1680x0 --rotate normal --output HDMI-0 --mode 1600x900 --pos 3600x180 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --pos 1680x1080 --rotate normal --output DP-0 --off --output DP-1 --off --output DP-2 --mode 1366x768 --pos 314x312 --rotate normal --output DP-3 --off --output VGA-1-0 --mode 1920x1080 --pos 3600x1080 --rotate normal --output DVI-1-0 --mode 1680x1050 --pos 0x1080 --rotate normal
``

Sometimes EXWM 0.28 and 0.30 also started broken like this:
![screenshotBroken28](https://github.com/user-attachments/assets/d9011929-7cbc-42f2-a626-922d0ffadb4a)
But after moving some screen in arandr, it corrected itself:
![Screenshot28Fixed](https://github.com/user-attachments/assets/fcc51a74-bea3-4fd7-8ff6-9001bab8a4ab)
With 0.31 it is no longer the case, frames are positioned in very weird places:
![broken3](https://github.com/user-attachments/assets/a93322f7-249c-4bc5-9168-ce18b3c68982)
![broken2](https://github.com/user-attachments/assets/45d58a6d-7b47-4f01-9040-9e75a5f3944b)
![broken4](https://github.com/user-attachments/assets/3de7d282-9841-44c3-b2fe-6f0896e068e5)

Here is minimal config that works for all monitors in EXWM 0.30

```elisp
(require 'package)
(package-initialize)
(setq user-emacs-directory "/home/{user}/.microWm/")
(setq user-init-file "/home/{user}/.microWm/init.el")

(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/") t)

(require 'exwm)
(require 'exwm-randr)

(setq exwm-workspace-number 12)
(setq current-randr-command "xrandr --output DVI-D-0 --mode 1920x1080 --pos 1680x0 --rotate normal --output HDMI-0 --mode 1600x900 --pos 3600x180 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --pos 1680x1080 --rotate normal --output DP-0 --off --output DP-1 --off --output DP-2 --mode 1366x768 --pos 314x312 --rotate normal --output DP-3 --off --output VGA-1-0 --mode 1920x1080 --pos 3600x1080 --rotate normal --output DVI-1-0 --mode 1680x1050 --pos 0x1080 --rotate normal")
(setq exwm-randr-workspace-monitor-plist '(0 "DVI-1-0" ;Fujistsu left bottom 1680x1650
					  1 "DVI-1-0"
					  2 "HDMI-1" ;Fujistsu center bottom FHD
					  3 "HDMI-1"
					  4 "VGA-1-0" ;Hp right bottom FHD
					  5 "VGA-1-0"
					  6 "DP-2"    ;AOC left top 1366x768
					  7 "DP-2"
					  8 "DVI-D-0" ;Acer center top FHD
					  9 "DVI-D-0"
					  10 "HDMI-0" ;Benq right top 1600x900
					  11 "HDMI-0"
					  ))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
	     "xrandr" nil current-randr-command)))
(exwm-randr-mode 1)
;;(exwm-randr-enable) ;;for 0.30 and lower
;; Disable menu-bar, tool-bar and scroll-bar to increase the usable space.
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

(ido-mode 1)
(setq ido-show-dot-for-dired t)

;; Global keybindings can be defined with `exwm-input-global-keys'.
(setq exwm-input-global-keys
      `(
        ;; Bind "s-r" to exit char-mode and fullscreen mode.
        ([?\s-r] . exwm-reset)
        ;; Bind "s-w" to switch workspace interactively.
        ([?\s-w] . exwm-workspace-switch)
        ;; Bind "s-&" to launch applications ('M-&' also works if the output
        ;; buffer does not bother you).
        (,(kbd "s-;") . (lambda (command)
			  (interactive (list (read-shell-command "$ ")))
			  (start-process-shell-command command nil command)))))
(exwm-enable)

(custom-set-variables
 '(package-selected-packages '(exwm xelb compat)))
(custom-set-faces
 )
```

I checked the docs and I don't think anything should be changed except for enabling the minor mode.

Emacs version: "29.3"
EXWM: 0.31
Xelb: 0.20
Package installed from elpa
Os: GNU/Linux Mint 21.2

**Comment by Stebalien** [comment]
Are you using any compositors (picom)?

**Comment by qespr** [comment]
No, honestly I didn't even know what compositor was until I looked it up now. 
But I can give it a try if it might help.

**Comment by Stebalien** [comment]
Nah, I just brought it up because the latest release of picom had a bug that sounded like what you described.

I'm not really sure what change in EXWM could have caused, this, to be honest.

- Are you seeing any warnings/messages?
- What if you connect just one external monitor? To external monitors?

**Comment by qespr** [comment]
>Are you seeing any warnings/messages?

If you mean some warning/error buffer then no
>What if you connect just one external monitor? To external monitors?

Well they're all external, it's a desktop, but weird things happen. 
With one screen only it works fine but there is a fat black line on the bottom.

When I use just 2 monitors with same resolution **next to** to each other, everything is fine, I can put them both on the left or right.
![correct1](https://github.com/user-attachments/assets/86f00cc0-553e-4a09-8481-ef88dfb53f42)
But if I put them above each other, one frame is gone and the monitor is just black:
![wrong2](https://github.com/user-attachments/assets/9e202d14-0b76-4366-980e-a47be1f2a852)
And with ``HDMI-1`` on top (frame with arandr is gone somewhere):
![wrongAbove](https://github.com/user-attachments/assets/c22a07e4-9ada-4a29-a32d-eb0f55aa75f3)
This still makes some kind of sense, but when I put them next to each other and cover one with the other a little, the one that's higher will cut off the lower one by the amount of overlap
![cutoff](https://github.com/user-attachments/assets/59997bf7-fdfa-4c41-88d1-bdeefd4c9900)
When I put them all next to each other, the order is broken and some get cut off:
![nope](https://github.com/user-attachments/assets/ba7d284c-e258-4594-9ab6-d965d887d755)
If I keep only 3 monitors, all with **same resolution and next to each other** it's also broken (result the same with any order of monitors)
![3fucked2](https://github.com/user-attachments/assets/4e552974-1ef9-4e45-bd3e-351994fac631)

**Comment by Stebalien** [comment]
What happens if you run the following snippet?

```elisp
(dolist (frame (frame-list))
  (when-let ((geo (frame-parameter frame 'exwm-geometry)))
    (redisplay t)
    (with-slots (width height) geo
      (set-frame-size frame
                      (- width (frame-fringe-width frame))
                      (- height (tab-bar-height frame t)) t))))
```

**Comment by Stebalien** [comment]
The most relevant changes in 0.31 were dd9c11125f5f917076ac2d6cec955f837c387891 and dad0668fc8162effe5eb66d821606ad80484484f.

So, what happens if you call `exwm-randr-refresh`?

**Comment by qespr** [comment]
>What happens if you run the following snippet?

Nothing
>So, what happens if you call ``exwm-randr-refresh``? I'm wondering if this is related to issues receiving randr events.

Yup, everything is fixed and seems to be working. I feel like I should have thought of that. It really seems that the issue will be receiving randr events. Thanks very much for help, I don't know what I'd do without EXWM.

In case anyone would need it, I put this my init:
```elisp
(run-with-timer 5 nil #'exwm-randr-refresh)
```

**Comment by Stebalien** [comment]
Re-opening because this is definitely a bug.

**Comment by Stebalien** [comment]
Actually, could you test with https://github.com/emacs-exwm/exwm/commit/f00b5ca655a0471a10d21a3e75b1a442a8d28941? Just evaling the modified `exwm-randr--on-Notify` function should be enough.

**Comment by qespr** [comment]
Works perfectly and when put into init, WM starts correctly right away

**Comment by Stebalien** [comment]
@minad how are you feeling about a 0.32 release?

**Comment by minad** [comment]
@Stebalien Great, so it turns out that this issue has already been fixed. Tagging a new release 0.32 sounds good. EXWM seems solid in its current form. I can do this later today.

**Comment by minad** [comment]
Done:

- https://github.com/emacs-exwm/exwm/commit/1485fcf064cee1766444472b09a681654c68636e
- https://github.com/emacs-exwm/exwm/releases/tag/0.32
- https://github.com/emacs-exwm/exwm/wiki/Home/_compare/f282ea06cdae0cb0079bb663559a07ecc465cae3...19d4b1a2c67f5db891d7d428b7b9a2e5722cbd1a
