### ISSUE TITLE
Focusing minibuffer from X11 window causes "Buffer is read only" error

### ISSUE THREAD

**Issue by lrustand** [emacs-exwm/exwm#93]
How to reproduce:

1. Open an X11 terminal emulator, for example xterm
2. Run `emacsclient -e '(completing-read "Prompt: " (list "1" "2" "3"))'`
3. Select something from the list
4. Try to type something into the X11 terminal.

The first keypress after the minibuffer is closed seems to go to the underlying emacs buffer of the EXWM window instead of to the X11 window inside it, causing a "Buffer is read only" error. Subsequent keypresses after the first one is sent correctly to the X11 window.

EDIT: Note that this only happens if the minibuffer is opened by other means than through a keybind. If I open the minibuffer by pressing `M-x`, 'C-x b' or similar, then the focus is returned correctly to the X11 window.

**Comment by Stebalien** [comment]
- What EXWM and Emacs version?
- What completion system? Can you reproduce with `emacsclient -e '(read-string "prompt: ")'`?

I remember reporting this ages ago (https://github.com/ch11ng/exwm/issues/253), but I haven't seen this issue in a while.

**Comment by lrustand** [comment]
> What EXWM and Emacs version?

- GNU Emacs 30.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
- EXWM 0.32

> What completion system?

I'm normally using Vertico, but have tested with Ivy also. Both produce the same behaviour. I'm also not the only one experiencing

>  Can you reproduce with emacsclient -e '(read-string "prompt: ")'?

I can partly reproduce with read-string by aborting it without accepting any input, which will produce the described behaviour. If I accept an entered string it seems to work correctly.

The issue was first reported to me here: https://github.com/lrustand/qutebrowser.el/issues/7.

**Comment by Stebalien** [comment]
Ooh. Interesting. I was trying it with alacrity and couldn't reproduce, but I can reproduce with xterm.

**Comment by lrustand** [comment]
Okay, that is strange. I have the same issue no matter what is the "source" of the command. As you can see in the issue I linked, and in the following discussion in https://github.com/lrustand/qutebrowser.el/pull/9, it also happens when emacsclient is invoked from qutebrowser, and it can even be reproduced without the use of emacsclient (using a unix socket for direct communication instead).

I tested with some more terminal emulators (konsole, urxvt, kitty, terminator) now just in case, but every single one of them show the exact same behaviour. I don't think this is dependent on which one you use.

I even tested running the emacsclient from another tty while an X11 window was the active buffer in EXWM, and this reproduces as well.

**Comment by Stebalien** [comment]
:man_facepalming: you're right, this reproduces everywhere. I'm sorry about that.

I have a snippet in my personal config that makes EXWM buffers read/write re-plays all text entered into EXWM buffers into the correct EXWM window (to get let regular emacs commands write into X windows). Unfortunately, that was masking this issue.

**Comment by Stebalien** [comment]
Ok, with vertico at least, the issue is:

1. On exiting the minibuffer, the pre-command hook runs for `vertico-exit` but not the post-command hook.
2. Then we try to enter a character and fail because `exwm-input--during-command` is non-nil.

I _think_ this is an Emacs issue (`real-this-command`) also doesn't get reset.

However, I'm not even sure if the `exwm-input--during-command` mechanism is necessary anymore after https://github.com/emacs-exwm/exwm/commit/8ea607ba8548e193157c5627ca30e3e57431ba5f. When I remove it, everything still seems to work (although that'll require more testing).

**Comment by Stebalien** [comment]
Note: you can "fix" it for `completing-read` by adding `vertico-exit` to `exwm-input-pre-post-command-blacklist`. But I'm going to try removing all this code because:

1. I don't think it's necessary anymore.
2. `emacsclient -e '(yes-or-no-p "foo")'` is broken as well.

**Comment by lrustand** [comment]
I've tested both your quick fix and your PR, and both seem to mostly solve the problem. It now works flawlessly when completing-read or other commands finish succesfully. It still happens if the completing-read is aborted without accepting an entry, but this might be a separate issue.

**Comment by Stebalien** [comment]
Hm. You're right, it still happens in that case. I also see the `emacsclient` command hang until pressing a key so something interesting is happening there.

**Comment by minad** [comment]
The issue occurs also wwith `emacsclient -e '(sit-for 3)'`

**Comment by lrustand** [comment]
But this secondary issue seems to only happen with emacsclient. Other ways of remotely triggering completing-read has been fully fixed by your workaround. For example, sending the command through a unix socket like this works fine even if the command is aborted:

```elisp
(make-network-process :name "eval-listener"
                        :family 'local
                        :service "/tmp/emacs-eval"
                        :server t
                        :filter (lambda (proc string)
                                  (eval (read string)))
                        :coding 'utf-8)
```

And then in xterm:
```
echo "(completing-read \"Prompt:\" '(\"1\" \"2\" \"3\"))" | socat - UNIX-CONNECT:/tmp/emacs-eval
```

(This did previously reproduce the original issue, but has now been fully fixed)

**Comment by minad** [comment]
The `sit-for` problem also doesn't occur when `completing-read` is wrapped in a `condition-case` which catches signals and errors. So I am not sure if we really have to handle this and have to advise `sit-for`. Maybe if there are other problems too?

**Comment by lrustand** [comment]
Is there any good reason why emacsclient is doing this? It sounds like an unnecessary thing to explicitly create a delay like that.

**Comment by Stebalien** [comment]
Yeah, I _think_ it's from `server-return-error` (then `server--message-sit-for`) but I didn't keep the stack trace.
