### ISSUE TITLE
Crash when minibuffer text scale is increased greatly

### ISSUE THREAD

**Issue by josephmturner** [emacs-exwm/exwm#98]
On `GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)`, EXWM version `0.28`.

In a fresh Emacs session, open Firefox.  It takes up the entire frame.
Open the minibuffer, e.g., with `M-x eval-expression`.
Run `text-scale-adjust` with `C-x C-=`.  The minibuffer text gets bigger.  Repeatedly press `C-=` until Emacs crashes, bringing you back to the login prompt.

Thank you!!

**Comment by minad** [comment]
I don't see this crash on Emacs 30 with EXWM 0.32. Usually crashes are problems in Emacs itself and not in packages, as long as the package does not mess with low-level code or native modules.

**Comment by josephmturner** [comment]
Thanks.  It appears that X11 is crashing.  [Reported] to Emacs bug tracker](https://yhetil.org/emacs-bugs/87msgrgwe4.fsf@breatheoutbreathe.in/T/#u).
